src/Esmeraldaplus.Web/Controllers/ContactenosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Esmeraldaplus.Web.Controllers
{
    public class ContactenosController : Controller
    {
        // GET: ContactenosController
        public ActionResult Index()
        {
            return View();
        }

        public IActionResult Index1()
        {
            return View();
        }

        // GET: ContactenosController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ContactenosController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ContactenosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ContactenosController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ContactenosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ContactenosController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ContactenosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/Esmeraldaplus.Web/Controllers/InfoProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Esmeraldaplus.Web.Controllers
{
    public class InfoProductoController : Controller
    {
        // GET: InfoProductoController
        public ActionResult Producto1()
        {
            return View();
        }
        public IActionResult Producto2()
        {
            return View();
        }
        public IActionResult Producto3()
        {
            return View();
        }
        public IActionResult Producto4()
        {
            return View();
        }
        public IActionResult Producto5()
        {
            return View();
        }
        public IActionResult Producto6()
        {
            return View();
        }
        public IActionResult Producto7()
        {
            return View();
        }
        public IActionResult Producto8()
        {
            return View();
        }
        public IActionResult Producto9()
        {
            return View();
        }
        // GET: InfoProductoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: InfoProductoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InfoProductoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InfoProductoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: InfoProductoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InfoProductoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: InfoProductoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/Esmeraldaplus.Web/Views/InfoProducto/Producto1.cshtml
@{
    ViewData["Title"] = "Producto1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Vista_Genelar {
    <link rel="stylesheet" href="../css/buy.css">
    <link rel="stylesheet" href="../css/fonts.css">
}

<nav>
    <ul>
        <li><a asp-area="" asp-controller="Home" asp-action="Index1">Inicio</a></li>
        <li><a asp-area="" asp-controller="Productos" asp-action="Catalogo1">Productos</a></li>
        <li><a asp-area="" asp-controller="QuienesSomos" asp-action="Index1">Quienes Somos</a></li>
        <li><a asp-area="" asp-controller="Contactenos" asp-action="Index1">Contactenos</a></li>
    </ul>
</nav>

<div class="menu">
    <span class="icon-menu"> Menu</span>
</div>

<div class="buy">

    <div class="image">
        <img src="../image/trajes.jpg" alt="">
    </div>

    <div class="information">
        <h1>Trajes Antifluido</h1>
        <p>
            Los trajes antifluidos poseen gran resistencia al rasgado, frote y deslizamiento en superficies,
            es completamente reutilizable de una sola pieza con capucha y cremallera frontal, rápido secado,
            fácil cuidado, y viene equipado con costuras de seguridad que evitan la exposición a sustancias,
            líquidos, partículas o virus
        </p>
    </div>

    <div class="cart">
        <a href=""><span class="icon-cart"></span>Agregar al Carrito</a>
        <a href=""><span class="icon-credit-card"></span>Comprar</a>
    </div>

</div>

src/Esmeraldaplus.Web/Views/InfoProducto/Producto2.cshtml
@{
    ViewData["Title"] = "Producto2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Vista_Genelar {
    <link rel="stylesheet" href="../css/buy.css">
    <link rel="stylesheet" href="../css/fonts.css">
}

<nav>
    <ul>
        <li><a asp-area="" asp-controller="Home" asp-action="Index1">Inicio</a></li>
        <li><a asp-area="" asp-controller="Productos" asp-action="Catalogo1">Productos</a></li>
        <li><a asp-area="" asp-controller="QuienesSomos" asp-action="Index1">Quienes Somos</a></li>
        <li><a asp-area="" asp-controller="Contactenos" asp-action="Index1">Contactenos</a></li>
    </ul>
</nav>

<div class="menu">
    <span class="icon-menu"> Menu</span>
</div>

<div class="buy">

    <div class="image">
        <img src="../image/alcoholes.jpg" alt="">
    </div>

    <div class="information">
        <h1>ALCOHOL ANTISÉPTICO</h1>
        <p>
            ALCOHOL ANTISÉPTICO se utiliza para la desinfección de la piel,
            utensilios, equipo y material de laboratorio. De uso directo.
            (Sirve también en la antisepsia cutánea). Útil para la desinfección en clínicas,
            hospitales, instituciones, industrias alimenticias, agroindustrias, etc.
        </p>
    </div>

    <div class="cart">
        <a href=""><span class="icon-cart"></span>Agregar al Carrito</a>
        <a href=""><span class="icon-credit-card"></span>Comprar</a>
    </div>

</div>

src/Esmeraldaplus.Web/Views/InfoProducto/Producto3.cshtml
@{
    ViewData["Title"] = "Producto3";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Vista_Genelar {
    <link rel="stylesheet" href="../css/buy.css">
    <link rel="stylesheet" href="../css/fonts.css">
}

<nav>
    <ul>
        <li><a asp-area="" asp-controller="Home" asp-action="Index1">Inicio</a></li>
        <li><a asp-area="" asp-controller="Productos" asp-action="Catalogo1">Productos</a></li>
        <li><a asp-area="" asp-controller="QuienesSomos" asp-action="Index1">Quienes Somos</a></li>
        <li><a asp-area="" asp-controller="Contactenos" asp-action="Index1">Contactenos</a></li>
    </ul>
</nav>

<div class="menu">
    <span class="icon-menu"> Menu</span>
</div>

<div class="buy">

    <div class="image">
        <img src="../image/jabones.jpg" alt="">
    </div>

    <div class="information">
        <h1>JABON ANTIBACTERIAL</h1>
        <p>
            Este tipo de jabón contiene ingredientes antimicrobianos cuya
            función principal es controlar la contaminación por microorganismos,
            trayendo consigo la prevención de enfermedades como infecciones de
            piel y gastrointestinales, entre otras.
        </p>
    </div>

    <div class="cart">
        <a href=""><span class="icon-cart"></span>Agregar al Carrito</a>
        <a href=""><span class="icon-credit-card"></span>Comprar</a>
    </div>

</div>

src/Esmeraldaplus.Web/Views/InfoProducto/Producto4.cshtml
@{
    ViewData["Title"] = "Producto4";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Vista_Genelar {
    <link rel="stylesheet" href="../css/buy.css">
    <link rel="stylesheet" href="../css/fonts.css">
}

<nav>
    <ul>
        <li><a asp-area="" asp-controller="Home" asp-action="Index1">Inicio</a></li>
        <li><a asp-area="" asp-controller="Productos" asp-action="Catalogo1">Productos</a></li>
        <li><a asp-area="" asp-controller="QuienesSomos" asp-action="Index1">Quienes Somos</a></li>
        <li><a asp-area="" asp-controller="Contactenos" asp-action="Index1">Contactenos</a></li>
    </ul>
</nav>

<div class="menu">
    <span class="icon-menu"> Menu</span>
</div>

<div class="buy">

    <div class="image">
        <img src="../image/geles.jpg" alt="">
    </div>

    <div class="information">
        <h1>Gel Antibacterial</h1>
        <p>Gel antibacterial o alcohol en Gel presenta la manera más práctica de mantener una higiene a cualquier hora del día y en cualquier lugar. ... Mata gérmenes comunes sin agua o toalla, es un gel formulado para proporcionar una especial acción descontaminante y desinfectante sobre superficies.</p>
    </div>

    <div class="cart">
        <a href=""><span class="icon-cart"></span>Agregar al Carrito</a>
        <a href=""><span class="icon-credit-card"></span>Comprar</a>
    </div>

</div>

src/Esmeraldaplus.Web/Views/InfoProducto/Producto5.cshtml
@{
    ViewData["Title"] = "Producto5";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Vista_Genelar {
    <link rel="stylesheet" href="../css/buy.css">
    <link rel="stylesheet" href="../css/fonts.css">
}

<nav>
    <ul>
        <li><a asp-area="" asp-controller="Home" asp-action="Index1">Inicio</a></li>
        <li><a asp-area="" asp-controller="Productos" asp-action="Catalogo1">Productos</a></li>
        <li><a asp-area="" asp-controller="QuienesSomos" asp-action="Index1">Quienes Somos</a></li>
        <li><a asp-area="" asp-controller="Contactenos" asp-action="Index1">Contactenos</a></li>
    </ul>
</nav>

<div class="menu">
    <span class="icon-menu"> Menu</span>
</div>

<div class="buy">

    <div class="image">
        <img src="../image/Tapabocas_de_tela_adidas_TALLA_XS-S_(PACK_DE_3)_(UNISEX)_Negro_H13185_01_laydown.jpg" alt="">
    </div>

    <div class="information">
        <h1>TapaBocas</h1>
        <p>El cubrebocas o tapabocas es un utensilio esencial para evitar la contaminación microbiológica emitida por la boca y la nariz. Por ello, su principal función es impedir el contacto de estas cuando se manipulan alimentos u otros productos que puedan verse contaminados.</p>
    </div>

    <div class="cart">
        <a href=""><span class="icon-cart"></span>Agregar al Carrito</a>
        <a href=""><span class="icon-credit-card"></span>Comprar</a>
    </div>

</div>

src/Esmeraldaplus.Web/Views/InfoProducto/Producto6.cshtml
@{
    ViewData["Title"] = "Producto6";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Vista_Genelar {
    <link rel="stylesheet" href="../css/buy.css">
    <link rel="stylesheet" href="../css/fonts.css">
}

<nav>
    <ul>
        <li><a asp-area="" asp-controller="Home" asp-action="Index1">Inicio</a></li>
        <li><a asp-area="" asp-controller="Productos" asp-action="Catalogo1">Productos</a></li>
        <li><a asp-area="" asp-controller="QuienesSomos" asp-action="Index1">Quienes Somos</a></li>
        <li><a asp-area="" asp-controller="Contactenos" asp-action="Index1">Contactenos</a></li>
    </ul>
</nav>

<div class="menu">
    <span class="icon-menu"> Menu</span>
</div>

<div class="buy">

    <div class="image">
        <img src="../image/fumigadora.jpg" alt="">
    </div>

    <div class="information">
        <h1>Fumigadora</h1>
        <p>Una fumigadora es una máquina agrícola encargada de fumigar zonas de terreno. La tarea de fumigar consiste en esparcir un compuesto plaguicida de diferentes formas, para proteger un cultivo o un terreno de agentes nocivos para el mismo.</p>
    </div>

    <div class="cart">
        <a href=""><span class="icon-cart"></span>Agregar al Carrito</a>
        <a href=""><span class="icon-credit-card"></span>Comprar</a>
    </div>

</div>

src/Esmeraldaplus.Web/Views/InfoProducto/Producto7.cshtml
@{
    ViewData["Title"] = "Producto7";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Vista_Genelar {
    <link rel="stylesheet" href="../css/buy.css">
    <link rel="stylesheet" href="../css/fonts.css">
}

<nav>
    <ul>
        <li><a asp-area="" asp-controller="Home" asp-action="Index1">Inicio</a></li>
        <li><a asp-area="" asp-controller="Productos" asp-action="Catalogo1">Productos</a></li>
        <li><a asp-area="" asp-controller="QuienesSomos" asp-action="Index1">Quienes Somos</a></li>
        <li><a asp-area="" asp-controller="Contactenos" asp-action="Index1">Contactenos</a></li>
    </ul>
</nav>

<div class="menu">
    <span class="icon-menu"> Menu</span>
</div>

<div class="buy">

    <div class="image">
        <img src="../image/cuaternario.jpg" alt="">
    </div>

    <div class="information">
        <h1>Líquido cuaternario</h1>
        <p>es un detergente desinfectante de alto poder germicida. No necesita enjuague.Es idóneo para ser usado en toda superficie lavable, tales como pisos, paredes, azulejos, espejos, sanitarios. Es recomendado para la desinfección diaria de baños, colegios, hospitales, geriátricos.</p>
    </div>

    <div class="cart">
        <a href=""><span class="icon-cart"></span>Agregar al Carrito</a>
        <a href=""><span class="icon-credit-card"></span>Comprar</a>
    </div>

</div>

src/Esmeraldaplus.Web/Views/InfoProducto/Producto8.cshtml
@{
    ViewData["Title"] = "Producto8";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Vista_Genelar {
    <link rel="stylesheet" href="../css/buy.css">
    <link rel="stylesheet" href="../css/fonts.css">
}

<nav>
    <ul>
        <li><a asp-area="" asp-controller="Home" asp-action="Index1">Inicio</a></li>
        <li><a asp-area="" asp-controller="Productos" asp-action="Catalogo1">Productos</a></li>
        <li><a asp-area="" asp-controller="QuienesSomos" asp-action="Index1">Quienes Somos</a></li>
        <li><a asp-area="" asp-controller="Contactenos" asp-action="Index1">Contactenos</a></li>
    </ul>
</nav>

<div class="menu">
    <span class="icon-menu"> Menu</span>
</div>

<div class="buy">

    <div class="image">
        <img src="../image/CHAQUETA.webp" alt="">
    </div>

    <div class="information">
        <h1>Chaqueta antifluido</h1>
        <p>Chaqueta de protección completa para la piel de tus brazos, torso, cuello, nariz y boca. Acabado anti fluido en su tela que repele líquidos y salpicaduras, funcionando como una barrera protectora. El tapabocas de la chaqueta NO reemplaza el uso del tapabocas facial.</p>
    </div>

    <div class="cart">
        <a href=""><span class="icon-cart"></span>Agregar al Carrito</a>
        <a href=""><span class="icon-credit-card"></span>Comprar</a>
    </div>

</div>

src/Esmeraldaplus.Web/Views/InfoProducto/Producto9.cshtml
@{
    ViewData["Title"] = "Producto9";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Vista_Genelar {
    <link rel="stylesheet" href="../css/buy.css">
    <link rel="stylesheet" href="../css/fonts.css">
}

<nav>
    <ul>
        <li><a asp-area="" asp-controller="Home" asp-action="Index1">Inicio</a></li>
        <li><a asp-area="" asp-controller="Productos" asp-action="Catalogo1">Productos</a></li>
        <li><a asp-area="" asp-controller="QuienesSomos" asp-action="Index1">Quienes Somos</a></li>
        <li><a asp-area="" asp-controller="Contactenos" asp-action="Index1">Contactenos</a></li>
    </ul>
</nav>

<div class="menu">
    <span class="icon-menu"> Menu</span>
</div>

<div class="buy">

    <div class="image">
        <img src="../image/Tapete.jpg" alt="">
    </div>

    <div class="information">
        <h1>Tapete desinfectante</h1>
        <p>Tapete de desinfección en líquido está conformado por un perfil grueso que lo rodea para retener la solución desinfectante (17 mm de altura útil ) y capacidad de almacenamiento de 10 litros x m2, con ranuras acanaladas que complementan la desinfección.</p>
    </div>

    <div class="cart">
        <a href=""><span class="icon-cart"></span>Agregar al Carrito</a>
        <a href=""><span class="icon-credit-card"></span>Comprar</a>
    </div>

</div>