src/Esmeraldaplus.Web/Controllers/InfoProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Esmeraldaplus.Web.Controllers
{
    public class InfoProductoController : Controller
    {
        // GET: InfoProductoController
        public ActionResult Producto1()
        {
            return View();
        }
        public IActionResult Producto2()
        {
            return View();
        }
        public IActionResult Producto3()
        {
            return View();
        }
        public IActionResult Producto4()
        {
            return View();
        }
        public IActionResult Producto5()
        {
            return View();
        }
        public IActionResult Producto6()
        {
            return View();
        }
        public IActionResult Producto7()
        {
            return View();
        }
        public IActionResult Producto8()
        {
            return View();
        }
        public IActionResult Producto9()
        {
            return View();
        }
        // GET: InfoProductoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: InfoProductoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InfoProductoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InfoProductoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: InfoProductoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InfoProductoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: InfoProductoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/Esmeraldaplus.Web/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Esmeraldaplus.Core.Domain;
using Esmeraldaplus.Infrastructure.Data;

namespace Esmeraldaplus.Web.Controllers
{
    public class ProductoController : Controller
    {
        private readonly EsmeraldaplusDbContext _context;

        public ProductoController(EsmeraldaplusDbContext context)
        {
            _context = context;
        }

        // GET: Producto
        public async Task<IActionResult> Index()
        {
            var esmeraldaplusDbContext = _context.Producto.Include(p => p.IdTipoProductoNavigation);
            return View(await esmeraldaplusDbContext.ToListAsync());
        }

        public IActionResult Catalogo()
        {
            return View();
        }

        public IActionResult Catalogo1()
        {
            return View();
        }

        // GET: Producto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto
                .Include(p => p.IdTipoProductoNavigation)
                .FirstOrDefaultAsync(m => m.IdProducto == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Producto/Create
        public IActionResult Create()
        {
            ViewData["IdTipoProducto"] = new SelectList(_context.TipoDeProducto, "IdTipoProducto", "IdTipoProducto");
            return View();
        }

        // POST: Producto/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdProducto,CantidaadProducto,IdTipoProducto,Descripcion,PrecioProducto")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdTipoProducto"] = new SelectList(_context.TipoDeProducto, "IdTipoProducto", "IdTipoProducto", producto.IdTipoProducto);
            return View(producto);
        }

        // GET: Producto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            ViewData["IdTipoProducto"] = new SelectList(_context.TipoDeProducto, "IdTipoProducto", "IdTipoProducto", producto.IdTipoProducto);
            return View(producto);
        }

        // POST: Producto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdProducto,CantidaadProducto,IdTipoProducto,Descripcion,PrecioProducto")] Producto producto)
        {
            if (id != producto.IdProducto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.IdProducto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdTipoProducto"] = new SelectList(_context.TipoDeProducto, "IdTipoProducto", "IdTipoProducto", producto.IdTipoProducto);
            return View(producto);
        }

        // GET: Producto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto
                .Include(p => p.IdTipoProductoNavigation)
                .FirstOrDefaultAsync(m => m.IdProducto == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // POST: Producto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producto = await _context.Producto.FindAsync(id);
            _context.Producto.Remove(producto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(int id)
        {
            return _context.Producto.Any(e => e.IdProducto == id);
        }
    }
}

src/Esmeraldaplus.Web/Controllers/homeadminController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Esmeraldaplus.Web.Controllers
{
    public class homeadminController : Controller
    {
        // GET: homeadminController
        public ActionResult Index()
        {
            return View();
        }

        // GET: homeadminController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: homeadminController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: homeadminController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: homeadminController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: homeadminController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: homeadminController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: homeadminController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/Esmeraldaplus.Web/Views/Producto/Catalogo.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
 
   @{
        ViewData["Title"] = "Catalogo";
        Layout = "~/Views/Shared/plantilla.cshtml";
    }

    @section home {
        <link rel="stylesheet" href="../css/products.css">
    }


    <div class="menu">
        <span class="icon-menu"> Menu</span>
    </div>


    <div class="container">
        <div class="objets">
            <div class="user">
                <img src="../image/alcoholes.jpg" alt="">
                <p>ALCOHOL ANTISÉPTICO se utiliza para la desinfección de la piel, utensilios, equipo y material de laboratorio. De uso directo. (Sirve también en la antisepsia cutánea). Útil para la desinfección en clínicas, hospitales, instituciones, industrias alimenticias, agroindustrias, etc.</p>
                @if (SignInManager.IsSignedIn(User))
                {
                    <a asp-area="" asp-controller="InfoProducto" asp-action="Producto2">Comprar</a>
                }
                else
                {
                    <a asp-area="Identity" asp-page="/Account/Login">Comprar</a>
                }


            </div>
            <div class="user">
                <img src="../image/trajes.jpg" alt="">
                <p>Los trajes antifluidos poseen gran resistencia al rasgado, frote y deslizamiento en superficies, es completamente reutilizable de una sola pieza con capucha y cremallera frontal, rápido secado, fácil cuidado, y viene equipado con costuras de seguridad que evitan la exposición a sustancias, líquidos, partículas o virus </p>
                @if (SignInManager.IsSignedIn(User))
                {
                    <a asp-area="" asp-controller="InfoProducto" asp-action="Producto1">Comprar</a>
                }
                else
                {
                    <a asp-area="Identity" asp-page="/Account/Login">Comprar</a>
                }


            </div>
            <div class="user">
                <img src="../image/jabones.jpg" alt="">
                <p>Este tipo de jabón contiene ingredientes antimicrobianos cuya función principal es controlar la contaminación por microorganismos, trayendo consigo la prevención de enfermedades como infecciones de piel y gastrointestinales, entre otras.</p>
                @if (SignInManager.IsSignedIn(User))
                {
                    <a asp-area="" asp-controller="InfoProducto" asp-action="Producto3">Comprar</a>
                }
                else
                {
                    <a asp-area="Identity" asp-page="/Account/Login">Comprar</a>
                }


            </div>

            <div class="user">
                <img src="../image/geles.jpg" alt="">
                <p>Gel antimaterial o alcohol en Gel presenta la manera más práctica de mantener una higiene a cualquier hora del día y en cualquier lugar. ... Mata gérmenes comunes sin agua o toalla, es un gel formulado para proporcionar una especial acción descontaminante y desinfectante sobre superficies.</p>
                @if (SignInManager.IsSignedIn(User))
                {
                    <a asp-area="" asp-controller="InfoProducto" asp-action="Producto4">Comprar</a>
                }
                else
                {
                    <a asp-area="Identity" asp-page="/Account/Login">Comprar</a>
                }

            </div>
            <div class="user">
                <img src="../image/Tapabocas_de_tela_adidas_TALLA_XS-S_(PACK_DE_3)_(UNISEX)_Negro_H13185_01_laydown.jpg" alt="">
                <p>El cubrebocas o tapabocas es un utensilio esencial para evitar la contaminación microbiológica emitida por la boca y la nariz. Por ello, su principal función es impedir el contacto de estas cuando se manipulan alimentos u otros productos que puedan verse contaminados.</p>
                @if (SignInManager.IsSignedIn(User))
                {
                    <a asp-area="" asp-controller="InfoProducto" asp-action="Producto5">Comprar</a>
                }
                else
                {
                    <a asp-area="Identity" asp-page="/Account/Login">Comprar</a>
                }


            </div>
            <div class="user">
                <img src="../image/fumigadora.jpg" alt="">
                <p>Una fumigadora es una máquina agrícola encargada de fumigar zonas de terreno. La tarea de fumigar consiste en esparcir un compuesto plaguicida de diferentes formas, para proteger un cultivo o un terreno de agentes nocivos para el mismo.</p>
                @if (SignInManager.IsSignedIn(User))
                {
                    <a asp-area="" asp-controller="InfoProducto" asp-action="Producto6">Comprar</a>
                }
                else
                {
                    <a asp-area="Identity" asp-page="/Account/Login">Comprar</a>
                }


            </div>

            <div class="user">
                <img src="../image/cuaternario.jpg" alt="">
                <p>es un detergente desinfectante de alto poder germicida. No necesita enjuague.Es idóneo para ser usado en toda superficie lavable, tales como pisos, paredes, azulejos, espejos, sanitarios. Es recomendado para la desinfección diaria de baños, colegios, hospitales, geriátricos.</p>
                @if (SignInManager.IsSignedIn(User))
                {
                    <a asp-area="" asp-controller="InfoProducto" asp-action="Producto7">Comprar</a>
                }
                else
                {
                    <a asp-area="Identity" asp-page="/Account/Login">Comprar</a>
                }


            </div>
            <div class="user">
                <img src="../image/CHAQUETA.webp" alt="">
                <p>Chaqueta de protección completa para la piel de tus brazos, torso, cuello, nariz y boca. Acabado anti fluido en su tela que repele líquidos y salpicaduras, funcionando como una barrera protectora. El tapabocas de la chaqueta NO reemplaza el uso del tapabocas facial.</p>
                @if (SignInManager.IsSignedIn(User))
                {
                    <a asp-area="" asp-controller="InfoProducto" asp-action="Producto8">Comprar</a>
                }
                else
                {
                    <a asp-area="Identity" asp-page="/Account/Login">Comprar</a>
                }


            </div>
            <div class="user">
                <img src="../image/Tapete.jpg" alt="">
                <p>Tapete de desinfección en líquido está conformado por un perfil grueso que lo rodea para retener la solución desinfectante (17 mm de altura útil ) y capacidad de almacenamiento de 10 litros x m2, con ranuras acanaladas que complementan la desinfección.</p>
                @if (SignInManager.IsSignedIn(User))
                {
                    <a asp-area="" asp-controller="InfoProducto" asp-action="Producto9">Comprar</a>
                }
                else
                {
                    <a asp-area="Identity" asp-page="/Account/Login">Comprar</a>
                }


            </div>
        </div>
    </div>

src/Esmeraldaplus.Web/Views/Producto/Catalogo1.cshtml
@{ ViewData["Title"] = "Catalogo1";
   Layout = "~/Views/Shared/plantilla.cshtml"; }

@section home {
    <link rel="stylesheet" href="../css/products.css">
}


<div class="menu">
    <span class="icon-menu"> Menu</span>
</div>


<div class="container">
    <div class="objets">
        <div class="user">
            <img src="../image/alcoholes.jpg" alt="">
            <p>ALCOHOL ANTISÉPTICO se utiliza para la desinfección de la piel, utensilios, equipo y material de laboratorio. De uso directo. (Sirve también en la antisepsia cutánea). Útil para la desinfección en clínicas, hospitales, instituciones, industrias alimenticias, agroindustrias, etc.</p>
            <a asp-area="" asp-controller="InfoProducto" asp-action="Producto2">Comprar</a>

        </div>
        <div class="user">
            <img src="../image/trajes.jpg" alt="">
            <p>Los trajes antifluidos poseen gran resistencia al rasgado, frote y deslizamiento en superficies, es completamente reutilizable de una sola pieza con capucha y cremallera frontal, rápido secado, fácil cuidado, y viene equipado con costuras de seguridad que evitan la exposición a sustancias, líquidos, partículas o virus </p>
            <a asp-area="" asp-controller="InfoProducto" asp-action="Producto1">Comprar</a>

        </div>
        <div class="user">
            <img src="../image/jabones.jpg" alt="">
            <p>Este tipo de jabón contiene ingredientes antimicrobianos cuya función principal es controlar la contaminación por microorganismos, trayendo consigo la prevención de enfermedades como infecciones de piel y gastrointestinales, entre otras.</p>
            <a asp-area="" asp-controller="InfoProducto" asp-action="Producto3">Comprar</a>

        </div>

        <div class="user">
            <img src="../image/geles.jpg" alt="">
            <p>Gel antimaterial o alcohol en Gel presenta la manera más práctica de mantener una higiene a cualquier hora del día y en cualquier lugar. ... Mata gérmenes comunes sin agua o toalla, es un gel formulado para proporcionar una especial acción descontaminante y desinfectante sobre superficies.</p>
            <a asp-area="" asp-controller="InfoProducto" asp-action="Producto4">Comprar</a>
        </div>
        <div class="user">
            <img src="../image/Tapabocas_de_tela_adidas_TALLA_XS-S_(PACK_DE_3)_(UNISEX)_Negro_H13185_01_laydown.jpg" alt="">
            <p>El cubrebocas o tapabocas es un utensilio esencial para evitar la contaminación microbiológica emitida por la boca y la nariz. Por ello, su principal función es impedir el contacto de estas cuando se manipulan alimentos u otros productos que puedan verse contaminados.</p>
            <a asp-area="" asp-controller="InfoProducto" asp-action="Producto5">Comprar</a>

        </div>
        <div class="user">
            <img src="../image/fumigadora.jpg" alt="">
            <p>Una fumigadora es una máquina agrícola encargada de fumigar zonas de terreno. La tarea de fumigar consiste en esparcir un compuesto plaguicida de diferentes formas, para proteger un cultivo o un terreno de agentes nocivos para el mismo.</p>
            <a asp-area="" asp-controller="InfoProducto" asp-action="Producto6">Comprar</a>

        </div>

        <div class="user">
            <img src="../image/cuaternario.jpg" alt="">
            <p>es un detergente desinfectante de alto poder germicida. No necesita enjuague.Es idóneo para ser usado en toda superficie lavable, tales como pisos, paredes, azulejos, espejos, sanitarios. Es recomendado para la desinfección diaria de baños, colegios, hospitales, geriátricos.</p>
            <a asp-area="" asp-controller="InfoProducto" asp-action="Producto7">Comprar</a>

        </div>
        <div class="user">
            <img src="../image/CHAQUETA.webp" alt="">
            <p>Chaqueta de protección completa para la piel de tus brazos, torso, cuello, nariz y boca. Acabado anti fluido en su tela que repele líquidos y salpicaduras, funcionando como una barrera protectora. El tapabocas de la chaqueta NO reemplaza el uso del tapabocas facial.</p>
            <a asp-area="" asp-controller="InfoProducto" asp-action="Producto8">Comprar</a>

        </div>
        <div class="user">
            <img src="../image/Tapete.jpg" alt="">
            <p>Tapete de desinfección en líquido está conformado por un perfil grueso que lo rodea para retener la solución desinfectante (17 mm de altura útil ) y capacidad de almacenamiento de 10 litros x m2, con ranuras acanaladas que complementan la desinfección.</p>
            <a asp-area="" asp-controller="InfoProducto" asp-action="Producto9  ">Comprar</a>

        </div>
    </div>
</div>

src/Esmeraldaplus.Web/Views/Producto/Create.cshtml
@model Esmeraldaplus.Core.Domain.Producto

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/crud.cshtml";
}

<link href="~/css/crear_datos.css" rel="stylesheet" />

<h1>Crear</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" class="contenido">
            <label asp-for="IdProducto" class="control-label">Id</label>
            <input asp-for="IdProducto" class="form-control" />
            <span asp-validation-for="IdProducto" class="text-danger"></span>

            <label asp-for="CantidaadProducto" class="control-label"></label>
            <input asp-for="CantidaadProducto" class="form-control" />
            <span asp-validation-for="CantidaadProducto" class="text-danger"></span>

            <label asp-for="IdTipoProducto" class="control-label"></label>
            <select asp-for="IdTipoProducto" class="form-control" asp-items="ViewBag.IdTipoProducto"></select>
            <span asp-validation-for="IdTipoProducto" class="text-danger"></span>


            <label asp-for="Descripcion" class="control-label"></label>
            <input asp-for="Descripcion" class="form-control" />
            <span asp-validation-for="Descripcion" class="text-danger"></span>


            <label asp-for="PrecioProducto" class="control-label"></label>
            <input asp-for="PrecioProducto" class="form-control" />
            <span asp-validation-for="PrecioProducto" class="text-danger"></span>


            <input type="submit" value="Crear" class="btn btn-primary" id="btn-crear" />
            <a asp-action="Index" class="back">Back to List</a>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Esmeraldaplus.Web/Views/Producto/Delete.cshtml
@model Esmeraldaplus.Core.Domain.Producto

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/crud.cshtml";
}

<link href="~/css/borrar.css" rel="stylesheet" />


<div class="contenido">
    <h3>BORRAR PRODUCTO</h3>
    <p>ID Producto: @Html.DisplayFor(model => model.IdProducto)</p>
    <p>Cantidad del Producto: @Html.DisplayFor(model => model.CantidaadProducto)</p>
    <p>Descripción: @Html.DisplayFor(model => model.Descripcion)</p>
    <p>Precio Porducto: @Html.DisplayFor(model => model.PrecioProducto)</p>
    <p>Id Tipo Producto: @Html.DisplayFor(model => model.IdTipoProductoNavigation.IdTipoProducto)</p>
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdProducto" />
        <input type="submit" value="Delete" class="btn btn-danger delete" /> |
        <a asp-action="Index" class="back">Back to List</a>
    </form>
</div>

src/Esmeraldaplus.Web/Views/Producto/Details.cshtml
@model Esmeraldaplus.Core.Domain.Producto

@{
    ViewData["Title"] = "Detalles de Producto";
    Layout = "~/Views/Shared/crud.cshtml";

}

<link href="~/css/detalles.css" rel="stylesheet" />


<div class="contenido">
    <h3>DETALLES DEL PRODUCTO</h3>
    <p>ID Producto: @Html.DisplayFor(model => model.IdProducto)</p>
    <p>Cantidad del Producto: @Html.DisplayFor(model => model.CantidaadProducto)</p>
    <p>Descripción: @Html.DisplayFor(model => model.Descripcion)</p>
    <p>Precio Porducto: @Html.DisplayFor(model => model.PrecioProducto)</p>
    <p>Id Tipo Producto: @Html.DisplayFor(model => model.IdTipoProductoNavigation.IdTipoProducto)</p>
    <a asp-action="Edit" asp-route-id="@Model.IdProducto" class="edit">Edit</a>
    <a asp-action="Index" class="back">Back to List</a>
</div>

src/Esmeraldaplus.Web/Views/Producto/Edit.cshtml
@model Esmeraldaplus.Core.Domain.Producto

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/crud.cshtml";
}

<link href="~/css/actualizar_datos.css" rel="stylesheet" />

<h1>Actualizar</h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" class="contenido">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdProducto" />
            
                <label asp-for="CantidaadProducto" class="control-label"></label>
                <input asp-for="CantidaadProducto" class="form-control" />
                <span asp-validation-for="CantidaadProducto" class="text-danger"></span>
            
                <label asp-for="IdTipoProducto" class="control-label"></label>
                <select asp-for="IdTipoProducto" class="form-control" asp-items="ViewBag.IdTipoProducto"></select>
                <span asp-validation-for="IdTipoProducto" class="text-danger"></span>
            
            
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            
            
                <label asp-for="PrecioProducto" class="control-label"></label>
                <input asp-for="PrecioProducto" class="form-control" />
                <span asp-validation-for="PrecioProducto" class="text-danger"></span>
            
            
                <input type="submit" value="Save" class="btn btn-primary" id="btn-crear"/>
                <a asp-action="Index" class="back">Back to List</a>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Esmeraldaplus.Web/Views/Producto/Index.cshtml
@model IEnumerable<Esmeraldaplus.Core.Domain.Producto>

@{
    ViewData["Title"] = "lista de producos";
    Layout = "~/Views/Shared/plantilla - admin.cshtml";
}

<link href="~/css/list_product.css" rel="stylesheet" />

<main>
    <div class="menu-admin">
        <a asp-area="" asp-controller="homeadmin" asp-action="Index"><span class="icon-home icon1"></span><br><p>Inicio</p></a>
        <a asp-area="" asp-controller="usuarios" asp-action="Index"><span class="icon-user icon2"></span><br><p>Lista de Usuarios</p></a>
        <a asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage"><span class="icon-user-check icon3"><br><p>Config. Cuenta</p></span></a>
        <a asp-area="" asp-controller="producto" asp-action="Index"><span class="icon-inventory icon4"><br><p>Productos</p></span></a>
        <a asp-area="" asp-controller="inventario" asp-action="Index"><span class="icon-inventory icon5"><br><p>Inventario</p></span></a>
    </div>
</main>


<p class="create">
    <a asp-action="Create" class="add">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Id Producto
            </th>
            <th>
                Cantidaad Producto
            </th>
            <th>
                Descripción
            </th>
            <th>
                Precio Producto
            </th>
            <th>
                Id Tipo Producto
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdProducto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CantidaadProducto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecioProducto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdTipoProductoNavigation.NombreProducto)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdProducto" class="actualizar">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.IdProducto" class="detalles">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.IdProducto" class="borrar">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>